### PR TITLE
Change error notice in Linux Platform

### PR DESCRIPTION
**Pull request by drajathasan**

### CODE REVIEW

**Comment by matlam** [comment]
Shouldn't there be an error message for windows was well? Maybe you can just use the first part of the message for windows

**Comment by drajathasan** [comment]
> Shouldn't there be an error message for windows was well? Maybe you can just use the first part of the message for windows

I was try in Windows too, and I recorded the process in my short video.

[Demo](https://youtu.be/_zmPWPb8b0I)

**Comment by matlam** [comment]
I'm sorry, I didn't see the last part of the error message from your commit("NB : you won't find issue with this if you are using ms-windows"). Why do you think that this is not a problem that can happen in Windows?

**Comment by drajathasan** [comment]
Becaise, basicly Windows directory is always writeable for other user include Apache daemon user. You can see my video in this link  : https://m.youtube.com/watch?feature=youtu.be&v=_zmPWPb8b0I  . I recorded it when I try my modification in Windows.

**Pull request closed without merging**
